name: smb
channels:
  - conda-forge
dependencies:
  - python=3.11
  - numpy=2.3
  - pandas=2.3
  - scipy=1.16
  - scikit-learn=1.7
  - xarray=2025.11
  - geopandas=1.1
  - matplotlib=3.10
  - netcdf4
  - pytorch=2.5
  - xgboost=3.2
  - lightgbm=4.6
